//#line 2 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the rqt_quadcoptergui package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __rqt_quadcoptergui__QUADCOPTERINTERFACECONFIG_H__
#define __rqt_quadcoptergui__QUADCOPTERINTERFACECONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace rqt_quadcoptergui
{
  class QuadcopterInterfaceConfigStatics;
  
  class QuadcopterInterfaceConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(QuadcopterInterfaceConfig &config, const QuadcopterInterfaceConfig &max, const QuadcopterInterfaceConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const QuadcopterInterfaceConfig &config1, const QuadcopterInterfaceConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, QuadcopterInterfaceConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const QuadcopterInterfaceConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, QuadcopterInterfaceConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const QuadcopterInterfaceConfig &config) const = 0;
      virtual void getValue(const QuadcopterInterfaceConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T QuadcopterInterfaceConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (QuadcopterInterfaceConfig::* field);

      virtual void clamp(QuadcopterInterfaceConfig &config, const QuadcopterInterfaceConfig &max, const QuadcopterInterfaceConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const QuadcopterInterfaceConfig &config1, const QuadcopterInterfaceConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, QuadcopterInterfaceConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const QuadcopterInterfaceConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, QuadcopterInterfaceConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const QuadcopterInterfaceConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const QuadcopterInterfaceConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, QuadcopterInterfaceConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, QuadcopterInterfaceConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<QuadcopterInterfaceConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(QuadcopterInterfaceConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("kpr"==(*i)->name){kpr = boost::any_cast<double>(val);}
        if("kdr"==(*i)->name){kdr = boost::any_cast<double>(val);}
        if("kpt"==(*i)->name){kpt = boost::any_cast<double>(val);}
        if("kdt"==(*i)->name){kdt = boost::any_cast<double>(val);}
        if("kit"==(*i)->name){kit = boost::any_cast<double>(val);}
        if("goalT"==(*i)->name){goalT = boost::any_cast<int>(val);}
        if("xg"==(*i)->name){xg = boost::any_cast<double>(val);}
        if("yg"==(*i)->name){yg = boost::any_cast<double>(val);}
        if("zg"==(*i)->name){zg = boost::any_cast<double>(val);}
        if("yawg"==(*i)->name){yawg = boost::any_cast<double>(val);}
        if("throtbound"==(*i)->name){throtbound = boost::any_cast<double>(val);}
        if("rpbound"==(*i)->name){rpbound = boost::any_cast<double>(val);}
        if("perturb_amp"==(*i)->name){perturb_amp = boost::any_cast<double>(val);}
        if("perturb_freq"==(*i)->name){perturb_freq = boost::any_cast<double>(val);}
        if("cmdrate_throttle"==(*i)->name){cmdrate_throttle = boost::any_cast<int>(val);}
        if("perturb_axis"==(*i)->name){perturb_axis = boost::any_cast<int>(val);}
      }
    }

    double kpr;
double kdr;
double kpt;
double kdt;
double kit;
int goalT;
double xg;
double yg;
double zg;
double yawg;
double throtbound;
double rpbound;
double perturb_amp;
double perturb_freq;
int cmdrate_throttle;
int perturb_axis;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double kpr;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double kdr;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double kpt;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double kdt;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double kit;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int goalT;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double xg;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double yg;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double zg;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double yawg;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double throtbound;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double rpbound;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double perturb_amp;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double perturb_freq;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int cmdrate_throttle;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int perturb_axis;
//#line 255 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("QuadcopterInterfaceConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const QuadcopterInterfaceConfig &__max__ = __getMax__();
      const QuadcopterInterfaceConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const QuadcopterInterfaceConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const QuadcopterInterfaceConfig &__getDefault__();
    static const QuadcopterInterfaceConfig &__getMax__();
    static const QuadcopterInterfaceConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const QuadcopterInterfaceConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void QuadcopterInterfaceConfig::ParamDescription<std::string>::clamp(QuadcopterInterfaceConfig &config, const QuadcopterInterfaceConfig &max, const QuadcopterInterfaceConfig &min) const
  {
    return;
  }

  class QuadcopterInterfaceConfigStatics
  {
    friend class QuadcopterInterfaceConfig;
    
    QuadcopterInterfaceConfigStatics()
    {
QuadcopterInterfaceConfig::GroupDescription<QuadcopterInterfaceConfig::DEFAULT, QuadcopterInterfaceConfig> Default("Default", "", 0, 0, true, &QuadcopterInterfaceConfig::groups);
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.kpr = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.kpr = 5.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.kpr = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("kpr", "double", 0, "Prop Gain on roll               , pitch", "", &QuadcopterInterfaceConfig::kpr)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("kpr", "double", 0, "Prop Gain on roll               , pitch", "", &QuadcopterInterfaceConfig::kpr)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.kdr = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.kdr = 5.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.kdr = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("kdr", "double", 0, "Derivative Gain on roll pitch", "", &QuadcopterInterfaceConfig::kdr)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("kdr", "double", 0, "Derivative Gain on roll pitch", "", &QuadcopterInterfaceConfig::kdr)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.kpt = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.kpt = 5.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.kpt = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("kpt", "double", 0, "Prop Gain on thrust", "", &QuadcopterInterfaceConfig::kpt)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("kpt", "double", 0, "Prop Gain on thrust", "", &QuadcopterInterfaceConfig::kpt)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.kdt = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.kdt = 5.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.kdt = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("kdt", "double", 0, "Derivative Gain on thrust", "", &QuadcopterInterfaceConfig::kdt)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("kdt", "double", 0, "Derivative Gain on thrust", "", &QuadcopterInterfaceConfig::kdt)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.kit = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.kit = 0.003;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.kit = 0.001;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("kit", "double", 0, "Integral Gain on thrust", "", &QuadcopterInterfaceConfig::kit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("kit", "double", 0, "Integral Gain on thrust", "", &QuadcopterInterfaceConfig::kit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.goalT = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.goalT = 20;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.goalT = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<int>("goalT", "int", 0, "Time to reach goal", "", &QuadcopterInterfaceConfig::goalT)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<int>("goalT", "int", 0, "Time to reach goal", "", &QuadcopterInterfaceConfig::goalT)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.xg = -3.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.xg = 3.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.xg = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("xg", "double", 2, "Final xposn", "", &QuadcopterInterfaceConfig::xg)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("xg", "double", 2, "Final xposn", "", &QuadcopterInterfaceConfig::xg)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.yg = -3.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.yg = 3.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.yg = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("yg", "double", 2, "Final yposn", "", &QuadcopterInterfaceConfig::yg)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("yg", "double", 2, "Final yposn", "", &QuadcopterInterfaceConfig::yg)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.zg = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.zg = 4.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.zg = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("zg", "double", 2, "Final zposn", "", &QuadcopterInterfaceConfig::zg)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("zg", "double", 2, "Final zposn", "", &QuadcopterInterfaceConfig::zg)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.yawg = -3.14;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.yawg = 3.14;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.yawg = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("yawg", "double", 2, "Final yawposn", "", &QuadcopterInterfaceConfig::yawg)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("yawg", "double", 2, "Final yawposn", "", &QuadcopterInterfaceConfig::yawg)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.throtbound = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.throtbound = 1.5;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.throtbound = 0.2;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("throtbound", "double", 0, "Max throttle value", "", &QuadcopterInterfaceConfig::throtbound)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("throtbound", "double", 0, "Max throttle value", "", &QuadcopterInterfaceConfig::throtbound)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.rpbound = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.rpbound = 40.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.rpbound = 20.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("rpbound", "double", 0, "Max roll/pitch value in deg", "", &QuadcopterInterfaceConfig::rpbound)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("rpbound", "double", 0, "Max roll/pitch value in deg", "", &QuadcopterInterfaceConfig::rpbound)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.perturb_amp = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.perturb_amp = 0.3;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.perturb_amp = 0.2;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("perturb_amp", "double", 0, "Amplitude of perturbation in m", "", &QuadcopterInterfaceConfig::perturb_amp)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("perturb_amp", "double", 0, "Amplitude of perturbation in m", "", &QuadcopterInterfaceConfig::perturb_amp)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.perturb_freq = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.perturb_freq = 5.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.perturb_freq = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("perturb_freq", "double", 0, "Freq of perturbation in Hz", "", &QuadcopterInterfaceConfig::perturb_freq)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<double>("perturb_freq", "double", 0, "Freq of perturbation in Hz", "", &QuadcopterInterfaceConfig::perturb_freq)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.cmdrate_throttle = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.cmdrate_throttle = 3;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.cmdrate_throttle = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<int>("cmdrate_throttle", "int", 0, "Reduce cmd publishing rate", "", &QuadcopterInterfaceConfig::cmdrate_throttle)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<int>("cmdrate_throttle", "int", 0, "Reduce cmd publishing rate", "", &QuadcopterInterfaceConfig::cmdrate_throttle)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.perturb_axis = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.perturb_axis = 3;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.perturb_axis = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<int>("perturb_axis", "int", 0, "Axis x,y,z(1,2,3)", "", &QuadcopterInterfaceConfig::perturb_axis)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr(new QuadcopterInterfaceConfig::ParamDescription<int>("perturb_axis", "int", 0, "Axis x,y,z(1,2,3)", "", &QuadcopterInterfaceConfig::perturb_axis)));
//#line 233 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(QuadcopterInterfaceConfig::AbstractGroupDescriptionConstPtr(new QuadcopterInterfaceConfig::GroupDescription<QuadcopterInterfaceConfig::DEFAULT, QuadcopterInterfaceConfig>(Default)));
//#line 390 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<QuadcopterInterfaceConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<QuadcopterInterfaceConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    QuadcopterInterfaceConfig __max__;
    QuadcopterInterfaceConfig __min__;
    QuadcopterInterfaceConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const QuadcopterInterfaceConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static QuadcopterInterfaceConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &QuadcopterInterfaceConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const QuadcopterInterfaceConfig &QuadcopterInterfaceConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const QuadcopterInterfaceConfig &QuadcopterInterfaceConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const QuadcopterInterfaceConfig &QuadcopterInterfaceConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<QuadcopterInterfaceConfig::AbstractParamDescriptionConstPtr> &QuadcopterInterfaceConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<QuadcopterInterfaceConfig::AbstractGroupDescriptionConstPtr> &QuadcopterInterfaceConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const QuadcopterInterfaceConfigStatics *QuadcopterInterfaceConfig::__get_statics__()
  {
    const static QuadcopterInterfaceConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = QuadcopterInterfaceConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __QUADCOPTERINTERFACERECONFIGURATOR_H__
